// resources/js/Components/EmptyState.svelte
<script>
    export let title = '';
    export let icon = '';
</script>

<div class="text-center py-12">
    {#if icon}
        <div class="mx-auto h-12 w-12 text-gray-400">
            {@html icon}
        </div>
    {/if}
    
    {#if title}
        <h3 class="mt-2 text-sm font-medium text-gray-900">{title}</h3>
    {/if}
    
    <div class="mt-1 text-sm text-gray-500">
        <slot />
    </div>
</div>

// resources/js/Components/EmptyState.vue
<template>
    <div class="text-center py-12">
        <svg v-if="!icon" class="mx-auto h-12 w-12 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 13V6a2 2 0 00-2-2H6a2 2 0 00-2 2v7m16 0v5a2 2 0 01-2 2H6a2 2 0 01-2-2v-5m16 0h-2.586a1 1 0 00-.707.293l-2.414 2.414a1 1 0 01-.707.293h-3.172a1 1 0 01-.707-.293l-2.414-2.414A1 1 0 006.586 13H4" />
        </svg>
        <component v-else :is="icon" class="mx-auto h-12 w-12 text-gray-400" />
        
        <h3 class="mt-2 text-sm font-medium text-gray-900 dark:text-gray-100">{{ title }}</h3>
        <p class="mt-1 text-sm text-gray-500 dark:text-gray-400">{{ description }}</p>
        
        <div v-if="$slots.default" class="mt-6">
            <slot />
        </div>
    </div>
</template>

<script setup>
defineProps({
    icon: {
        type: [Object, Function],
        default: null
    },
    title: {
        type: String,
        required: true
    },
    description: {
        type: String,
        default: ''
    }
});
</script>
